### ISSUE TITLE
Partial "checksum" feature

### ISSUE THREAD

**Issue by Arnaudv6** [hkbakke/rsync-backup#4]
from the read-me:

> rsync-backup grabs the internal checksums rsync is generating when transferring new files to avoid having to calculate the checksums manually. It also reuses all checksums for unchanged files from the previous backup, so in most cases no additional work is needed for a backup. It is however smart enough to detect if some files are missing its checksum and manually calculates the checksum for these files. This typically happens if a backup is stopped before completion and later resumed.

One of the points of doing checksum on backup, _-for me-_ is to detect any data rot/corruption. So this is not the right tool for me, if I understand correctly?
Here checksum is used as an additional meta information of the files, to distinguish between modified ones and unaltered ones?

**Comment by hkbakke** [comment]
rsync-backup grabs the checksums from the initial transfer of a file and stores the checksum together with the backup repository. The checksum of a file is only stored during initial transfer or if rsync detects that the file is modified in the source (validly). The point of storing these checksums is to be able to run verify against each backup to detect bitrot or files that have been modified on the backup side and not in the source since the backup was taken.

What rsync-backup will _not_ do is to fix a corrupt file. You must delete the corrupt file in the backup destination and take a new backup that will detect the missing file using ordinary rsync mechanisms and retransfer it. It will warn you however, and if you need to recover you can verify that the file is exactly like it was during the initial backup.

rsync-backup was however written for a time where I did not have any good open source alternatives that was simple to deploy without any infrastructure. Today I would use `borg` for these kinds of backup purposes as you also get encryption, block level deduplication and compression via SSH and because the repository is encrypted the target may be untrusted.

**Comment by Arnaudv6** [comment]
Hey, thanks @hkbakke for the detailed answer. Much appreciated. Have a nice day.
